### PR TITLE
Package data for plotting defaults

### PR DESCRIPTION
**Pull request by joshwlambert**
This PR addresses #4 by adding two data objects to {tracetheme}, one for the default plotting dimensions for vignettes (applied to the `demo.Rmd` vignette), and a second for the default plotting dimensions for figures for slideshows. 

I have kept this PR intentionally basic and to provide a platform for further development. Please suggest improvements to the values selected for the width and height of the new data files, as well as other figure defaults that may be useful (e.g. dpi) which can easily be added to the data (via `data-raw/` scripts). 

The data is available to users automatically (`LazyData: true`)

- [x] I have read the CONTRIBUTING guidelines 
- [ ] A new item has been added to `NEWS.md`
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by joshwlambert** [comment]
lintr workflow is failing due to `unused_import_linter` for {maps}. Not sure if this is a false positive as `library(maps)` is called in `demo.Rmd`. I seems this failing lintr is not due to changes from this PR. Happy to either fix within this PR, or merge and fix in a separate PR, let me know preferences.

**Comment by joshwlambert** [comment]
Thanks for testing, I've updated the `slides` data to use 6x3.

**Comment by Bisaloo** [comment]
> lintr workflow is failing due to `unused_import_linter` for {maps}. Not sure if this is a false positive as `library(maps)` is called in `demo.Rmd`. I seems this failing lintr is not due to changes from this PR. Happy to either fix within this PR, or merge and fix in a separate PR, let me know preferences.

Let's fix it here. You can remove the `library(maps)` line.

**Comment by Bisaloo** [comment]
Looks like we're moving forward with the dimensions proposed here.

Could you please:

- fix the lintr checks as indicated above?
- open an issue in packagetemplate to indicate these defaults should be used?

Thanks :pray:!

**Comment by joshwlambert** [comment]
> open an issue in packagetemplate to indicate these defaults should be used?
 
Logged in epiverse-trace/packagetemplate#131.

**Pull request merged**
